name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
      - name: Copy .env.example files
        run: find . -name ".env.example" -exec cp {} $(dirname {})/.env \;
      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint